package com.boilermake.studycentral.data;

import java.util.Calendar;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "groups")
public class Group {
	private String id;
	private String name;
	private Set<Integer> days;
	private Integer startHour;
	private Integer startMinute;
	private Integer endHour;
	private Integer endMinute;
	private Calendar creation;
	private String location;
	private Integer size;
	private Boolean open;
	private Integer maxSize;
	private Set<String> members;

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@DynamoDBAttribute
	public Set<Integer> getDays() {
		return days;
	}
	
	public void setDays(Set<Integer> days) {
		this.days = days;
	}
	
	@DynamoDBAttribute
	public Integer getStartHour() {
		return startHour;
	}
	
	public void setStartHour(Integer startHour) {
		this.startHour = startHour;
	}
	
	@DynamoDBAttribute
	public Integer getStartMinute() {
		return startMinute;
	}
	
	public void setStartMinute(Integer startMinute) {
		this.startMinute = startMinute;
	}
	
	@DynamoDBAttribute
	public Integer getEndHour() {
		return endHour;
	}
	
	public void setEndHour(Integer endHour) {
		this.endHour = endHour;
	}
	
	@DynamoDBAttribute
	public Integer getEndMinute() {
		return endMinute;
	}
	
	public void setEndMinute(Integer endMinute) {
		this.endMinute = endMinute;
	}
	
	@DynamoDBAttribute
	public String getLocation() {
		return location;
	}
	
	public void setLocation(String location) {
		this.location = location;
	}
	
	@DynamoDBAttribute
	public Integer getSize() {
		return size;
	}
	
	public void setSize(Integer size) {
		this.size = size;
	}
	
	@DynamoDBAttribute
	public Boolean getOpen() {
		return open;
	}
	
	public void setOpen(Boolean open) {
		this.open = open;
	}
	
	@DynamoDBAttribute
	public Integer getMaxSize() {
		return maxSize;
	}
	
	public void setMaxSize(Integer maxSize) {
		this.maxSize = maxSize;
	}
	
	@DynamoDBAttribute
	public Calendar getCreation() {
		return creation;
	}
	
	public void setCreation(Calendar creation) {
		this.creation = creation;
	}

	@DynamoDBAttribute
	public Set<String> getMembers() {
		return members;
	}

	public void setMembers(Set<String> members) {
		this.members = members;
	}
}
